### ISSUE TITLE
代码运行错误

### ISSUE THREAD

**Issue by changjh23** [mnzhang01/MD_Net#1]
您好，在您的main.py中有这样一行代码

`pyramid = list(pyramid_gaussian(imgs_trans, n_scales-1, multichannel=True))`

**multichannel=True**这是一个未定义的参数，导致整个程序运行不起来

**Comment by mnzhang01** [comment]
你更新一下scikit-image版本试试看呢？

**Comment by changjh23** [comment]
- 确实scikit_image的版本问题，我的是0.22版本，在0.19之后的版本中`multichannel`已经弃用了，现在采用的是`channel_axis`

- 现在有一个新问题，就是
`out_y2 = nn.functional.conv2d(skip_out2, out_k_m2, padding=0, groups =3,bias=None)`
`out_y1 = nn.functional.conv2d(skip_out1, out_k_m1, padding=0, groups =3,bias=None)`
`out_y0 = nn.functional.conv2d(skip_out0, out_k_m0, padding=0, groups =3,bias=None)`

  有一个报错：
  
  >`out_y0 = nn.functional.conv2d(skip_out0, out_k_m0, padding=0, groups =3,bias=None)`
  > RuntimeError: Given groups=3, weight of size [3, 3, 79, 79], expected input[1, 3, 589, 514] to have 9 channels, but got 3 channels instead

我自己尝试修改了一下，能跑通但是效果很差，想请问您一下是怎么回事

十分感谢

**Comment by mnzhang01** [comment]
我改成channel_axis会报tensor size不match的错误，multichannel不会出现这个错误。你换一下scikit_image的版本呢？如果还是不行的话，可以试着改一下模糊核的大小，重新跑一下试试。
